### ISSUE TITLE
TODO/FIXME Count 24

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-kms-http#26]
- [ ] TODO: do not use did:key but support a did:v1 based key.
       Commit: (0444a40) Refactor helpers.
       File:  [test/mocha/20-revocation.js:342](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/test/mocha/20-revocation.js#L342)
       Matthew Collier commented 4 months ago

  - [ ] TODO: map `signer.type` to signature suite
       Commit: (38eecdc) Generate a revocation capability.
       File:  [test/mocha/20-revocation.js:291](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/test/mocha/20-revocation.js#L291)
       Matthew Collier commented 5 months ago

  - [ ] FIXME: this is an axios error due to poor error handling in
       Commit: (0444a40) Refactor helpers.
       File:  [test/mocha/20-revocation.js:282](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/test/mocha/20-revocation.js#L282)
       Matthew Collier commented 4 months ago

  - [ ] TODO: with jsigs@5, err.cause should have additional details for assert
       Commit: (0444a40) Refactor helpers.
       File:  [test/mocha/20-revocation.js:263](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/test/mocha/20-revocation.js#L263)
       Matthew Collier commented 4 months ago

  - [ ] TODO: add zcap validator
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:277](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L277)
       Dave Longley commented a year ago

  - [ ] TODO: consider whether this should be exposed w/o authorization or not
       Commit: (296345a) Expose public key description information via HTTP.
       File:  [lib/http.js:257](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L257)
       Dave Longley commented a year ago

  - [ ] TODO: add endpoint for controller recovery/figure out what endpoint to
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:196](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L196)
       Dave Longley commented a year ago

  - [ ] TODO: add authorizations endpoint; include an authorization that allows
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:193](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L193)
       Dave Longley commented a year ago

  - [ ] TODO: review before future implementation...
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:192](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L192)
       Dave Longley commented a year ago

  - [ ] TODO: consider making this zcap authorized instead
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:182](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L182)
       Dave Longley commented a year ago

  - [ ] FIXME: in non-proxy mode, this code should determine what config
       Commit: (15a4d48) Add FIXME.
       File:  [lib/http.js:136](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L136)
       Dave Longley commented 5 months ago

  - [ ] FIXME: rework to use `controller` specified in `account` associated
       Commit: (13ab8c9) Add FIXME.
       File:  [lib/http.js:130](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L130)
       Dave Longley commented 5 months ago

  - [ ] TODO: add validator that requires security `@context` and `controller`
       Commit: (d1d3370) Add host application-based keystore recovery.
       File:  [lib/http.js:126](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L126)
       Dave Longley commented 10 months ago

  - [ ] TODO: implement `update` for keystore config
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:119](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L119)
       Dave Longley commented a year ago

  - [ ] TODO: consider returning only IDs and let other endpoint handle
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:114](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L114)
       Dave Longley commented a year ago

  - [ ] TODO: implement
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:106](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L106)
       Dave Longley commented a year ago

  - [ ] FIXME: any account can search for any controller's keystore configs
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:85](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L85)
       Dave Longley commented a year ago

  - [ ] TODO: implement query validator
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:82](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L82)
       Dave Longley commented a year ago

  - [ ] FIXME: any account can create any number of keystores, this should be
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:56](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L56)
       Dave Longley commented a year ago

  - [ ] TODO: perhaps the proxy option should be triggered via `cfg.proxy`
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:53](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L53)
       Dave Longley commented a year ago

  - [ ] TODO: endpoints for creating and deleting keystores will only use
       Commit: (7a48af6) Use keystores.
       File:  [lib/http.js:35](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http.js#L35)
       Dave Longley commented a year ago

  - [ ] TODO: add zcap validator
       Commit: (6b73dbc) Refactor helpers.
       File:  [lib/http-revocations.js:27](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/http-revocations.js#L27)
       Matthew Collier commented 5 months ago

  - [ ] TODO: support RsaSignature2018 and other suites?
       Commit: (6b73dbc) Refactor helpers.
       File:  [lib/helpers.js:40](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/helpers.js#L40)
       Matthew Collier commented 5 months ago

  - [ ] TODO: a lot of helper code here is in common w/ bedrock-data-hub-storage,
       Commit: (e1f8542) Add revocation get.
       File:  [lib/helpers.js:23](https://github.com/digitalbazaar/bedrock-kms-http/blob/master/lib/helpers.js#L23)
       Matthew Collier commented 5 months ago

**Comment by dlongley** [comment]
All remaining FIXMEs and TODOs have been updated in the code to refer to specific issues, closing.
